name: PlatformIO CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        example:
          - examples/basic
        conf:
          - esp32-idf4-arduino.ini
          - esp32-idf5-idf.ini
          - esp32s3-idf4-arduino.ini
          - esp32s3-idf5-idf.ini
          - esp32c3-idf4-arduino.ini
          - esp32c3-idf5-idf.ini
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install platformio
      - name: Build examples
        run: platformio ci --lib="." --project-conf="./test-inis/${{ matrix.conf }}"
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
